// Code generated by Slice Machine. DO NOT EDIT.

import GridComponent from './GridComponent';
import HeroBanner from './HeroBanner';
import ImageSlider from './ImageSlider';

export {
	GridComponent,
	HeroBanner,
	ImageSlider,
};

export const components = {
	grid_component: GridComponent,
	hero_banner: HeroBanner,
	image_slider: ImageSlider,
};
