// Code generated by Slice Machine. DO NOT EDIT.

import CanvasSlider from './CanvasSlider';
import Grid from './Grid';
import HeroBanner from './HeroBanner';
import ImageSlider from './ImageSlider';

export {
	CanvasSlider,
	Grid,
	HeroBanner,
	ImageSlider,
};

export const components = {
	canvas_slider: CanvasSlider,
	grid_component: Grid,
	hero_banner: HeroBanner,
	image_slider: ImageSlider,
};
